# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wiiggee1/Desktop/School/homeexam_d7032e

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wiiggee1/Desktop/School/homeexam_d7032e

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/wiiggee1/Desktop/School/homeexam_d7032e/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wiiggee1/Desktop/School/homeexam_d7032e/CMakeFiles /home/wiiggee1/Desktop/School/homeexam_d7032e//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wiiggee1/Desktop/School/homeexam_d7032e/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named apples2apples

# Build rule for target.
apples2apples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 apples2apples
.PHONY : apples2apples

# fast build rule for target.
apples2apples/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/build
.PHONY : apples2apples/fast

#=============================================================================
# Target rules for targets named CLI11

# Build rule for target.
CLI11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CLI11
.PHONY : CLI11

# fast build rule for target.
CLI11/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cli11_proj-build/src/CMakeFiles/CLI11.dir/build.make _deps/cli11_proj-build/src/CMakeFiles/CLI11.dir/build
.PHONY : CLI11/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.dir/build.make tests/CMakeFiles/tests.dir/build
.PHONY : tests/fast

src/events.o: src/events.cpp.o
.PHONY : src/events.o

# target to build an object file
src/events.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/events.cpp.o
.PHONY : src/events.cpp.o

src/events.i: src/events.cpp.i
.PHONY : src/events.i

# target to preprocess a source file
src/events.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/events.cpp.i
.PHONY : src/events.cpp.i

src/events.s: src/events.cpp.s
.PHONY : src/events.s

# target to generate assembly for a file
src/events.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/events.cpp.s
.PHONY : src/events.cpp.s

src/game.o: src/game.cpp.o
.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i
.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s
.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/game_cli.o: src/game_cli.cpp.o
.PHONY : src/game_cli.o

# target to build an object file
src/game_cli.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/game_cli.cpp.o
.PHONY : src/game_cli.cpp.o

src/game_cli.i: src/game_cli.cpp.i
.PHONY : src/game_cli.i

# target to preprocess a source file
src/game_cli.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/game_cli.cpp.i
.PHONY : src/game_cli.cpp.i

src/game_cli.s: src/game_cli.cpp.s
.PHONY : src/game_cli.s

# target to generate assembly for a file
src/game_cli.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/game_cli.cpp.s
.PHONY : src/game_cli.cpp.s

src/host.o: src/host.cpp.o
.PHONY : src/host.o

# target to build an object file
src/host.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/host.cpp.o
.PHONY : src/host.cpp.o

src/host.i: src/host.cpp.i
.PHONY : src/host.i

# target to preprocess a source file
src/host.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/host.cpp.i
.PHONY : src/host.cpp.i

src/host.s: src/host.cpp.s
.PHONY : src/host.s

# target to generate assembly for a file
src/host.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/host.cpp.s
.PHONY : src/host.cpp.s

src/joingame_state.o: src/joingame_state.cpp.o
.PHONY : src/joingame_state.o

# target to build an object file
src/joingame_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/joingame_state.cpp.o
.PHONY : src/joingame_state.cpp.o

src/joingame_state.i: src/joingame_state.cpp.i
.PHONY : src/joingame_state.i

# target to preprocess a source file
src/joingame_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/joingame_state.cpp.i
.PHONY : src/joingame_state.cpp.i

src/joingame_state.s: src/joingame_state.cpp.s
.PHONY : src/joingame_state.s

# target to generate assembly for a file
src/joingame_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/joingame_state.cpp.s
.PHONY : src/joingame_state.cpp.s

src/judge_state.o: src/judge_state.cpp.o
.PHONY : src/judge_state.o

# target to build an object file
src/judge_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/judge_state.cpp.o
.PHONY : src/judge_state.cpp.o

src/judge_state.i: src/judge_state.cpp.i
.PHONY : src/judge_state.i

# target to preprocess a source file
src/judge_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/judge_state.cpp.i
.PHONY : src/judge_state.cpp.i

src/judge_state.s: src/judge_state.cpp.s
.PHONY : src/judge_state.s

# target to generate assembly for a file
src/judge_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/judge_state.cpp.s
.PHONY : src/judge_state.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/network/client.o: src/network/client.cpp.o
.PHONY : src/network/client.o

# target to build an object file
src/network/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/network/client.cpp.o
.PHONY : src/network/client.cpp.o

src/network/client.i: src/network/client.cpp.i
.PHONY : src/network/client.i

# target to preprocess a source file
src/network/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/network/client.cpp.i
.PHONY : src/network/client.cpp.i

src/network/client.s: src/network/client.cpp.s
.PHONY : src/network/client.s

# target to generate assembly for a file
src/network/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/network/client.cpp.s
.PHONY : src/network/client.cpp.s

src/network/message.o: src/network/message.cpp.o
.PHONY : src/network/message.o

# target to build an object file
src/network/message.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/network/message.cpp.o
.PHONY : src/network/message.cpp.o

src/network/message.i: src/network/message.cpp.i
.PHONY : src/network/message.i

# target to preprocess a source file
src/network/message.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/network/message.cpp.i
.PHONY : src/network/message.cpp.i

src/network/message.s: src/network/message.cpp.s
.PHONY : src/network/message.s

# target to generate assembly for a file
src/network/message.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/network/message.cpp.s
.PHONY : src/network/message.cpp.s

src/network/server.o: src/network/server.cpp.o
.PHONY : src/network/server.o

# target to build an object file
src/network/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/network/server.cpp.o
.PHONY : src/network/server.cpp.o

src/network/server.i: src/network/server.cpp.i
.PHONY : src/network/server.i

# target to preprocess a source file
src/network/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/network/server.cpp.i
.PHONY : src/network/server.cpp.i

src/network/server.s: src/network/server.cpp.s
.PHONY : src/network/server.s

# target to generate assembly for a file
src/network/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/network/server.cpp.s
.PHONY : src/network/server.cpp.s

src/network/session_connections.o: src/network/session_connections.cpp.o
.PHONY : src/network/session_connections.o

# target to build an object file
src/network/session_connections.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/network/session_connections.cpp.o
.PHONY : src/network/session_connections.cpp.o

src/network/session_connections.i: src/network/session_connections.cpp.i
.PHONY : src/network/session_connections.i

# target to preprocess a source file
src/network/session_connections.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/network/session_connections.cpp.i
.PHONY : src/network/session_connections.cpp.i

src/network/session_connections.s: src/network/session_connections.cpp.s
.PHONY : src/network/session_connections.s

# target to generate assembly for a file
src/network/session_connections.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/network/session_connections.cpp.s
.PHONY : src/network/session_connections.cpp.s

src/play_state.o: src/play_state.cpp.o
.PHONY : src/play_state.o

# target to build an object file
src/play_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/play_state.cpp.o
.PHONY : src/play_state.cpp.o

src/play_state.i: src/play_state.cpp.i
.PHONY : src/play_state.i

# target to preprocess a source file
src/play_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/play_state.cpp.i
.PHONY : src/play_state.cpp.i

src/play_state.s: src/play_state.cpp.s
.PHONY : src/play_state.s

# target to generate assembly for a file
src/play_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/play_state.cpp.s
.PHONY : src/play_state.cpp.s

src/player.o: src/player.cpp.o
.PHONY : src/player.o

# target to build an object file
src/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/player.cpp.o
.PHONY : src/player.cpp.o

src/player.i: src/player.cpp.i
.PHONY : src/player.i

# target to preprocess a source file
src/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/player.cpp.i
.PHONY : src/player.cpp.i

src/player.s: src/player.cpp.s
.PHONY : src/player.s

# target to generate assembly for a file
src/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apples2apples.dir/build.make CMakeFiles/apples2apples.dir/src/player.cpp.s
.PHONY : src/player.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... CLI11"
	@echo "... apples2apples"
	@echo "... tests"
	@echo "... src/events.o"
	@echo "... src/events.i"
	@echo "... src/events.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/game_cli.o"
	@echo "... src/game_cli.i"
	@echo "... src/game_cli.s"
	@echo "... src/host.o"
	@echo "... src/host.i"
	@echo "... src/host.s"
	@echo "... src/joingame_state.o"
	@echo "... src/joingame_state.i"
	@echo "... src/joingame_state.s"
	@echo "... src/judge_state.o"
	@echo "... src/judge_state.i"
	@echo "... src/judge_state.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/network/client.o"
	@echo "... src/network/client.i"
	@echo "... src/network/client.s"
	@echo "... src/network/message.o"
	@echo "... src/network/message.i"
	@echo "... src/network/message.s"
	@echo "... src/network/server.o"
	@echo "... src/network/server.i"
	@echo "... src/network/server.s"
	@echo "... src/network/session_connections.o"
	@echo "... src/network/session_connections.i"
	@echo "... src/network/session_connections.s"
	@echo "... src/play_state.o"
	@echo "... src/play_state.i"
	@echo "... src/play_state.s"
	@echo "... src/player.o"
	@echo "... src/player.i"
	@echo "... src/player.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

